batch_size: 32
checkpoint: exps/debug/checkpoint/checkpoint_300.pth
device: cpu
exp_name: debug
learning_rate: 0.001
learning_rate_min: 1.0e-08
log_interval: 100
max_iter: 800
model_type: est_coord
num_workers: 0
obj_name: power_drill
point_num: 512
robot: galbot
save_interval: 800
seed: 0
val_interval: 800
val_num: 2
