batch_size: 64
checkpoint: exps/est_coord_ft_lr1e4/checkpoint/checkpoint_6500.pth
device: cuda
exp_name: est_coord_ft_lr3e5
learning_rate: 3.0e-05
learning_rate_min: 1.0e-06
log_interval: 100
max_iter: 8000
model_type: est_coord
num_workers: 2
obj_name: power_drill
point_num: 1024
robot: galbot
save_interval: 500
seed: 0
val_interval: 500
val_num: 10
